import 'package:flutter/material.dart';
import 'package:flutterapp/kd_20mediaapp/generatedwebsitewidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/kd_20mediaapp/generatedwebsitewidget/generated/GeneratedIconWidget.dart';
import 'package:flutterapp/kd_20mediaapp/generatedwebsitewidget/generated/GeneratedIcon2Widget.dart';
import 'package:flutterapp/kd_20mediaapp/generatedwebsitewidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/kd_20mediaapp/generatedwebsitewidget/generated/GeneratedGoalsWidget.dart';
import 'package:flutterapp/kd_20mediaapp/generatedwebsitewidget/generated/GeneratedHome1Widget.dart';

/* Frame Website
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWebsiteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 8000.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 8000.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1668.0,
                              right: null,
                              bottom: null,
                              width: 1920.0,
                              height: 976.0,
                              child: GeneratedGoalsWidget(),
                            ),
                            Positioned(
                              left: 1507.5,
                              top: 1198.0,
                              right: null,
                              bottom: null,
                              width: 578.0,
                              height: 562.0,
                              child: GeneratedIconWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1920.0,
                              height: 880.0,
                              child: GeneratedHome1Widget(),
                            ),
                            Positioned(
                              left: -95.0,
                              top: 829.0,
                              right: null,
                              bottom: null,
                              width: 338.0,
                              height: 317.0,
                              child: GeneratedIcon2Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 988.0,
                              right: null,
                              bottom: null,
                              width: 1920.0,
                              height: 680.0,
                              child: GeneratedFrame1Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 7174.0,
                              right: null,
                              bottom: null,
                              width: 1920.0,
                              height: 826.0,
                              child: GeneratedRectangle3Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
